version: 1.0.{build}

branches:
  only:
  - main
  
skip_tags: true

image: Visual Studio 2022

configuration:
#- Debug
- Release

clone_folder: c:/projects/KAIN2

build:
  project: c:/projects/KAIN2/Build/Build_Win32/Soul Reaver.sln
  verbosity: minimal
  
platform:
  - Win32
  #- x64
  
before_build:
  - cmd: cd %clone_folder%
  - cmd: git submodule update --init --recursive
  - cmd: cd Emulator
  - cmd: cd Platform
  - cmd: cd Windows
  - cmd: Generate-Project-Files.bat
  
artifacts:
   - path: Binaries/%configuration%/*.zip
     name: Binaries
  
after_build:
  - cmd: cd ../
  - cmd: dir
  - cmd: cd ../
  - cmd: dir
  - cmd: cd Binaries
  - cmd: dir
  - cmd: cd %configuration%
  - cmd: dir
  - 7z a KAIN2.zip %configuration%
