name: Delete Older Releases (Keep latest 15)
     
on:
  workflow_dispatch:
  
jobs:
  delete_releases:
    name: Delete Older Releases (Keep latest 15)
    runs-on: windows-latest
    steps:
        - name: Delete
          uses: dev-drprasad/delete-older-releases@v0.2.1
          
          with:
            keep_latest: 15
            delete_tags: true
          env:
            GITHUB_TOKEN: ${{secrets.PAT}}
