name: Emscripten Release Build

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release_web:
    name: Web Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v11
      
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/Build_EMSDK
        
      - name: Verify
        run: emcc -v

      - name: Configure CMake
        run: emcmake cmake . -B%cd%"/Build_EMSDK/"

      - name: Build
        run: cmake --build ./Build_EMSDK --config Release
