name: Emscripten Release Build

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main2'
      
jobs:
  release_web:
    name: Web Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
           token: ${{secrets.PAT}}
           submodules: 'true'
           
      - uses: mymindstorm/setup-emsdk@v12
      
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/Build/Build_EMSDK
        
      - name: Configure CMake        
        run: cmd.exe /k ${{github.workspace}}/External/libValkyrie/Platform/Emscripten/Generate-Project-Files-GHA.bat

      - name: Build
        run: cmake --build ${{github.workspace}}/Build/Build_EMSDK --config Release
      
      - name: Create Deployment Directory
        run: cmake -E make_directory ${{github.workspace}}/Build/Build_EMSDK/kain2/Deploy/
        
      - name: Copy to Deployment Folder
        run: copy ${{github.workspace}}/Build/Build_EMSDK/KAIN2/Game/KAIN2_Web.*  ${{github.workspace}}/Build/Build_EMSDK/KAIN2/Deploy/
        
      - name: Deploy to FTP
        uses: dennisameling/ftp-upload-action@v1.0.10
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASSWORD}}
          local_dir: ${{github.workspace}}/Build/Build_EMSDK/kain2/Deploy/
          server_dir: ./
          secure: false
        
